on:
  push:
    branches:
      - 'master'

jobs:
  ktlint:
    name: "Check ktlint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: ktlint
        run: ./gradlew ktlintCheck
  detekt:
    name: "Check detekt"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: detekt
        run: ./gradlew detekt
  test:
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Build debug
        run: ./gradlew assembleDebug
      - name: Tests
        run: ./gradlew testDebug